version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:80"  # Map port 9090 on your host to port 80 in the container
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wineindustry
      MYSQL_USER: wineindustry
      MYSQL_PASSWORD: wineindustry
    ports:
      - "3306:3306"  # Optional: expose MySQL port to host if needed
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"  # Map port 9091 on your host to port 80 in the container
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
